### ISSUE TITLE
Add `map` value type

### ISSUE THREAD

**Issue by YaroShkvorets** [streamingfast/substreams-entity-change#3]
I've ran into a case where I need to pass nested structure to a sink consuming `entity-changes`. 

What's stopping us from adding `map` type to [proto definition](https://github.com/streamingfast/substreams-entity-change/blob/b055bc3d12bc37b3dda9f32847476c692d8f1cd4/proto/sf/substreams/entity/v1/entity.proto#L34)? 
```
...
Map map = 7;
...
```
```
message Map {
  map<string, Value> entries = 1;
}
```

**Comment by maoueh** [comment]
The `graph-node` which consumes `EntityChange` don't know about this type, so that's why it cannot be added. At least in this from.
